#!/usr/bin/env python
# -*- coding: utf-8 -*-

from costmap import Costmap

import rospy
from nav_msgs.msg import OccupancyGrid, Odometry
from geometry_msgs.msg import Pose, Point
from sensor_msgs.msg import Image
from std_msgs.msg import String

import numpy as np
import cv2

import json
import math


class ObstacleDetector():
    def __init__(self):
        # ROS Subscriber
        self.__global_costmap_sub = rospy.Subscriber(
            "/move_base/global_costmap/costmap", OccupancyGrid, self.__global_costmap_cb, queue_size=1)
        self.__local_costmap_sub = rospy.Subscriber(
            "/move_base/local_costmap/costmap", OccupancyGrid, self.__local_costmap_cb, queue_size=1)
        self._odom_sub = rospy.Subscriber(
            "/odom", Odometry, self.__odm_cb, queue_size=1)
        self._twugo_method_sub = rospy.Subscriber(
            "/twugo_method", String, self.__set_next_vertex_pos, queue_size=1)
        self.__commander_sub =  rospy.Subscriber(
            "/obstacle_detector/detect_request", String, self.__obstacle_detect_cb, queue_size=1)

        # ROS Publisher
        self.__trimed_global_costmap_pub = rospy.Publisher(
            "/obstacle_detector/global_costmap/trimed", OccupancyGrid, queue_size=1, latch=True)
        self.__trimed_local_costmap_pub = rospy.Publisher(
            "/obstacle_detector/local_costmap/trimed", OccupancyGrid, queue_size=1, latch=True)
        self.__trimed_merged_costmap_pub = rospy.Publisher(
            "/obstacle_detector/merged_costmap/trimed", OccupancyGrid, queue_size=1)
        self.__obstacle_detect_pub = rospy.Publisher(
            "/obstacle_detector/msg", String, queue_size=1)

        self.__initial_global_costmap = None
        self.__local_costmap = None
        self.__threshold = 90
        self.__robot_positon = None
        self.__trimed_merged_costmap = None
        self.__next_vertex_pos = None
        self.__pre_vertex_pos = None
        self.__is_detect_request = False

    def main(self):
        rospy.spin()

    def __costmap_difference_from_global(self, global_costmap, local_costmap):
        h, w = global_costmap.get_size()
        blank_global_costmap = np.zeros((h, w), dtype='uint8')
        global_origin = global_costmap.get_origin()
        global_resolution = global_costmap.get_resolution()
        global_costmap_array = global_costmap.convert_array(global_array_func)
        local_costmap_array = local_costmap.convert_array(local_array_func)
        local_origin = local_costmap.get_origin()
        local_resolution = local_costmap.get_resolution()

        # When merge locam_costmap to blank_global_costmap, this data is need.
        padding_pix = dict(
            x = int((local_origin.position.x - global_origin.position.x) / global_resolution),
            y = int((local_origin.position.y - global_origin.position.y) / global_resolution),
            z = int((local_origin.position.z - global_origin.position.z) / global_resolution)
        )

        if local_resolution == global_resolution :
            h, w = local_costmap.get_size()
            for y in range(h):
                for x in range(w):
                    if not global_costmap_array[padding_pix['y'] + y][padding_pix['x'] + x] > self.__threshold:
                        blank_global_costmap[padding_pix['y'] + y][padding_pix['x'] + x] = local_costmap_array[y][x]
                    
        else:
            # TODO: If resolution is different between global_costmap and local_costmap, we must correspond.
            rospy.logwarn("[Obstacle detector] resolution is not match")
            return
        h, w = global_costmap.get_size()
        return Costmap(blank_global_costmap, h, w, global_resolution, global_origin)


    def __merge_costmap_local_costmap_to_global_costmap(self, global_costmap, local_costmap, global_array_func=lambda x:x, local_array_func=lambda x: x):
        h, w = global_costmap.get_size()
        blank_global_costmap = np.zeros((h, w), dtype='uint8')
        global_origin = global_costmap.get_origin()
        global_resolution = global_costmap.get_resolution()
        global_array = global_costmap.convert_array(global_array_func)
        for y in range(h):
            for x in range(w):
                blank_global_costmap[y][x] = global_array[y][x]

        local_array = local_costmap.convert_array(local_array_func)
        local_origin = local_costmap.get_origin()
        local_resolution = local_costmap.get_resolution()

        # When merge locam_costmap to blank_global_costmap, this data is need.
        padding_pix = dict(
            x = int((local_origin.position.x - global_origin.position.x) / global_resolution),
            y = int((local_origin.position.y - global_origin.position.y) / global_resolution),
            z = int((local_origin.position.z - global_origin.position.z) / global_resolution)
        )

        if local_resolution == global_resolution :
            h, w = local_costmap.get_size()
            for y in range(h):
                for x in range(w):
                    if blank_global_costmap[padding_pix['y'] + y][padding_pix['x'] + x] == 0:
                        blank_global_costmap[padding_pix['y'] + y][padding_pix['x'] + x] = local_array[y][x]
                    
        else:
            # TODO: If resolution is different between global_costmap and local_costmap, we must correspond.
            rospy.logwarn("[Obstacle detector] resolution is not match")
            return
        h, w = global_costmap.get_size()
        return Costmap(blank_global_costmap, h, w, global_resolution, global_origin)


    def __odm_cb(self, data):
        self.__robot_positon = Point()
        self.__robot_positon.x = data.pose.pose.position.x
        self.__robot_positon.y = data.pose.pose.position.y
        self.__robot_positon.z = data.pose.pose.position.z

    def __merge_costmap_arrays(self, costmap0, costmap1, costmap2=None, func0=lambda x: x, func1=lambda x: x, func2=lambda x: x,
                                 marker0=None, marker1=None, marker2=None, marker_size=10):
        height, width = costmap0.get_size()
        origin = costmap0.get_origin()
        resolution = costmap0.get_resolution()

        h, w = costmap1.get_size()
        if h != height or w != width:
            rospy.logerr_once("[Obstacle detector] costmap0 と costmap1 のサイズが異なります。merge する costmap のサイズは統一する必要があります。")
            return
        if origin != costmap1.get_origin():
            rospy.logerr_once("[Obstacle detector] costmap0 と costmap1 の position 又は orientation が異なります。merge する costmap の原点は統一する必要があります。")
            return
        if resolution != costmap1.get_resolution():
            rospy.logerr_once("[Obstacle detector] costmap0 と costmap1 の resolution が異なります。merge する costmap のresolutionは統一する必要があります。")
            return
        if costmap2 != None:
            h, w = costmap2.get_size()
            if h != height or w != width:
                rospy.logerr_once("[Obstacle detector] costmap0 と costmap2 のサイズが異なります。merge する costmap のサイズは統一する必要があります。")
                return
            if origin != costmap2.get_origin():
                rospy.logerr_once("[Obstacle detector] costmap0 と costmap2 の position 又は orientation が異なります。merge する costmap の原点は統一する必要があります。")
                return
            if resolution != costmap2.get_resolution():
                rospy.logerr_once("[Obstacle detector] costmap0 と costmap2 の resolution が異なります。merge する costmap のresolutionは統一する必要があります。")
                return
            merged_array = np.dstack((costmap0.convert_array(func0), costmap1.convert_array(func1), costmap2.convert_array(func2)))
        else:
            merged_array = np.dstack((costmap0.convert_array(func0), costmap1.convert_array(func1), np.zeros((height, width), dtype="uint8")))
        
        if marker0 == None and marker1 == None and marker2 == None:
            return merged_array
        
        start_point = Point()
        start_point.x = origin.position.x
        start_point.y = origin.position.y
        start_point.z = origin.position.z
        end_point = Point()
        end_point.x = origin.position.x + width * resolution
        end_point.y = origin.position.y + width * resolution
        end_point.z = origin.position.z

        if marker0 != None:
            if (start_point.x <= marker0.x and marker0.x <= end_point.x) and (start_point.y <= marker0.y and marker0.y <= end_point.y):
                cv2.drawMarker(merged_array, (int((marker0.x - start_point.x)/resolution), int((marker0.y - start_point.y)/resolution)),
                                (255, 0, 0), markerType=cv2.MARKER_CROSS, markerSize=marker_size, thickness=1, line_type=cv2.LINE_8)
            else:
                rospy.logwarn("[Obstacle detector] marker0 の描画位置が範囲外のため描画できませんでした")
        if marker1 != None:
            if (start_point.x <= marker1.x and marker1.x <= end_point.x) and (start_point.y <= marker1.y and marker1.y <= end_point.y):
                cv2.drawMarker(merged_array, (int((marker1.x - start_point.x)/resolution), int((marker1.y - start_point.y)/resolution)),
                                (0, 255, 0), markerType=cv2.MARKER_CROSS, markerSize=marker_size, thickness=1, line_type=cv2.LINE_8)
            else:
                rospy.logwarn("[Obstacle detector] marker1 の描画位置が範囲外のため描画できませんでした")
        if marker2 != None:
            if (start_point.x <= marker2.x and marker2.x <= end_point.x) and (start_point.y <= marker2.y and marker2.y <= end_point.y):
                cv2.drawMarker(merged_array, (int((marker2.x - start_point.x)/resolution), int((marker2.y - start_point.y)/resolution)),
                                (0, 0, 255), markerType=cv2.MARKER_CROSS, markerSize=marker_size, thickness=1, line_type=cv2.LINE_8)
            else:
                rospy.logwarn("[Obstacle detector] marker2 の描画位置が範囲外のため描画できませんでした")

        return merged_array

    def __global_costmap_cb(self, data):
        h, w = data.info.height, data.info.width
        costmap = np.array(data.data, dtype='uint8').reshape(h, w)
        if self.__initial_global_costmap is None:
            self.__initial_global_costmap = Costmap(
                costmap, data.info.height, data.info.width,
                data.info.resolution, data.info.origin)
            self.__trimed_global_costmap_pub.publish(self.__trim_costmap(self.__initial_global_costmap).converte_occupancy_grid())
        

    def __local_costmap_cb(self, data):
        h, w = data.info.height, data.info.width
        costmap = np.array(data.data, dtype='uint8').reshape(h, w)
        self.__local_costmap = Costmap(
                costmap, data.info.height, data.info.width,
                data.info.resolution, data.info.origin)
        
        if self.__initial_global_costmap != None:
            merged_array = self.__merge_costmap_local_costmap_to_global_costmap(self.__initial_global_costmap, self.__local_costmap)
            self.__trimed_merged_costmap = self.__trim_costmap(merged_array)
            self.__trimed_merged_costmap_pub.publish(self.__trimed_merged_costmap.converte_occupancy_grid())
        
        if self.__is_detect_request:
            self.__obstacle_detect(self.__local_costmap)
        
        self.__trimed_local_costmap_pub.publish(self.__trim_costmap(self.__local_costmap).converte_occupancy_grid())

    def __trim_costmap(self, costmap):
        start = dict(x=None, y=None)
        end = dict(x=None, y=None)

        costmap_array = costmap.get_array()
        height, width = costmap.get_size()
        
        # 縦方向の境界検索
        for s in range(height):
            e = height - s - 1
            if s > e:
                start["y"] = 0
                end["y"] = height - 1
                break
            
            if start["y"] == None and np.sum(costmap_array[s]) != 0:
                start["y"] = s
            if end["y"] == None and np.sum(costmap_array[e]) != 0:
                end["y"] = e

            if start["y"] != None and end["y"] != None:
                break
        if start["y"] == None:
            start["y"] = 0
        if end["y"] == None:
            end["y"] = height - 1
        
        # 横方向の境界検索
        start["x"], end["x"] = width - 1, 0
        for y in range(start["y"], end["y"] + 1):
            sx, ex = None, None
            for x in range(width):
                if costmap_array[y][x] != 0:
                    if sx == None:
                        sx = x
                    ex = x
            if (sx is not None) and (start["x"] > sx):
                start["x"] = sx
            if end["x"] < ex:
                end["x"] = ex
        if start["x"] > end["x"]:
            start["x"], end["x"] = 0, width - 1

        rospy.loginfo("[ObstacleDetector::__trim_costmap] start: %s" % start)
        rospy.loginfo("[ObstacleDetector::__trim_costmap] end: %s" % end)
        # 切り取り
        trim_h, trim_w = end["y"] - start["y"] + 1, end["x"] - start["x"] + 1
        trimed_costmap_array = np.zeros((trim_h, trim_w), dtype='uint8')
        for y in range(start["y"], end["y"] + 1):
            trimed_costmap_array[y-start["y"]] = costmap_array[y][start["x"]:end["x"]+1]
        resoluton = costmap.get_resolution()
        
        # TODO: orientation をどうすればいいかわからなかったため放置している
        costmap_origin = costmap.get_origin()
        trimed_origin = Pose()
        trimed_origin.position.x = costmap_origin.position.x
        trimed_origin.position.y = costmap_origin.position.y
        trimed_origin.position.z = costmap_origin.position.z
        trimed_origin.orientation.w = costmap_origin.orientation.w
        trimed_origin.orientation.x = costmap_origin.orientation.x
        trimed_origin.orientation.y = costmap_origin.orientation.y
        trimed_origin.orientation.z = costmap_origin.orientation.z
        trimed_origin.position.x += start["x"] * resoluton
        trimed_origin.position.y += start["y"] * resoluton
        # return trimed_costmap_array
        return Costmap(trimed_costmap_array, trim_h, trim_w, costmap.get_resolution(), trimed_origin)

    def __set_next_vertex_pos(self, data):
        payload = json.loads(data.data)
        if "is_goal" in payload and payload["is_goal"]:
            return
        if "x" in payload and "y" in payload:
            self.__next_vertex_pos = Point()
            self.__next_vertex_pos.x = payload["x"]
            self.__next_vertex_pos.y = payload["y"]
        if "pre_x" in payload and "pre_y" in payload:
            self.__pre_vertex_pos = Point()
            self.__pre_vertex_pos.x = payload["pre_x"]
            self.__pre_vertex_pos.y = payload["pre_y"]

    def __obstacle_detect_cb(self, data):
        self.__is_detect_request = True

    def __obstacle_detect(self, costmap):
        if costmap is None:
            return
        if self.__next_vertex_pos is None:
            return
        costmap_array = costmap.get_array()
        res = costmap.get_resolution()
        distance = math.sqrt((self.__pre_vertex_pos.x - self.__next_vertex_pos.x)**2 + (self.__pre_vertex_pos.y - self.__next_vertex_pos.y)**2) / res
        points = set()
        costmap_origin = costmap.get_origin()
        offset_x = costmap_origin.position.x * -1
        offset_y = costmap_origin.position.y * -1
        self.__calc_center_point(points, distance, ((self.__pre_vertex_pos.x + offset_x)/res, (self.__pre_vertex_pos.y + offset_y)/res), ((self.__next_vertex_pos.x + offset_x)/res, (self.__next_vertex_pos.y + offset_y)/res))
        height, width = costmap.get_size()
        for (x, y) in points:
            if not 0 <= x < width:
                continue
            if not 0 <= y < height:
                continue
            if costmap_array[y][x] >= self.__threshold:
                rospy.logwarn("[Obstacle detector] Detect obstacle!!")
                self.__obstacle_detect_pub.publish("detect_obstacle")
                break
        self.__is_detect_request = False

    def __calc_center_point(self, points, distance, start, end):
        if distance <= 0:
            return
        center_x = int((end[0] + start[0]) / 2)
        center_y = int((end[1] + start[1]) / 2)
        points.add((center_x, center_y))

        # 4近傍画素も追加
        points.add((center_x + 1, center_y))
        points.add((center_x - 1, center_y))
        points.add((center_x, center_y + 1))
        points.add((center_x, center_y - 1))
        self.__calc_center_point(points, distance//2, start, (center_x, center_y))
        self.__calc_center_point(points, distance//2, (center_x, center_y), end)


if __name__ == "__main__":
    rospy.init_node('obstacle_detector')
    obstacle_detector = ObstacleDetector()
    obstacle_detector.main()