#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# このノードは navigation スタックへの操作を経路ファイルから行います
# 

import rospy
import json
from std_msgs.msg import String
# from tf.transformations import euler_from_quaternion, quaternion_from_euler
# from tf import TransformListener
from nav_msgs.msg import Odometry
from rosgraph_msgs.msg import Log
# import actionlib
# from move_base_msgs.msg import MoveBaseAction, MoveBaseGoal
# from geometry_msgs.msg import Quaternion

class Commander():
    def __init__(self):
        self._rosout_sub = rospy.Subscriber("/rosout", Log, self.rosout_cb, queue_size=1)
        self._odom_sub = rospy.Subscriber("/odom", Odometry, self.odom_cb, queue_size=1)
        self._awsiot_to_ros_pub = rospy.Publisher("/awsiot_to_ros", String, queue_size=1)

    def main(self):
        rospy.spin()

    def rosout_cb(self, message):
        try:
            message_json = json.loads(message.data)
            payload = message_json["payload"]
            rospy.log(json.dumps(payload))

        except Exception as e:
            rospy.logwarn("navigation request failed")
            rospy.logwarn(e)
    
    def odom_cb(self, message):
        try:
            message_json = json.loads(message.data)
            payload = message_json["payload"]
        except Exception as e:
            rospy.logwarn("navigation request failed")
            rospy.logwarn(e)

def main():
    rospy.init_node('commander')
    commander = Commander()
    commander.main()        

if __name__ == '__main__':
    main()
