#!/usr/bin/env python
import rospy
from sensor_msgs.msg import Image 
from cv_bridge import CvBridge
import cv2

def process_image(msg):
    try:
        # rospy.loginfo("Will show image")
        bridge = CvBridge()
        orig = bridge.imgmsg_to_cv2(msg, "bgr8")
        # img = cv2.cvtColor(orig, cv2.COLOR_BGR2GRAY)
        cv2.imshow('image', orig)
        cv2.waitKey(1)
    except Exception as err:
        rospy.logerr("In img_proc, Error occured")
        rospy.logerr(err)

def start_node():
    rospy.init_node('img_proc')
    rospy.loginfo('img_proc node started')
    rospy.Subscriber("/camera/image", Image, process_image)
    rospy.spin()

if __name__ == '__main__':
    try:
        start_node()
    except rospy.ROSInterruptException:
        pass